### ISSUE TITLE
Clarifications around bot ban

### ISSUE THREAD

**Issue by kytwb** [nortxort/nortbot#12]
I got the bot banning people randomly in the room. I tried to figure why without looking at the code as I'm running out of time with work, but people have been telling me it's related to if a person send too many messages too fast?

By looking at the config, I see `StringBansFileName - File name for string bans`. Is it a blacklist of word? What is the separator for words? `\n` or `,`? Right now my instance of the bot has no StringBansFileName, not sure if it's using a default world list as a fallback or not (that would explain the "random ban").

**Comment by Technetium1** [comment]
@kytwb https://github.com/nortxort/nortbot/blob/954f322279457d47531da2bd40cfb2335798af62/handlers/check.py#L206 go here and change to:
```python
if ts.seconds == 0 and ts.microseconds < 400000:
```

**Comment by kytwb** [comment]
@Technetium1 shouldn't I increase the upper limit?

**Comment by nortxort** [comment]
The `StringBansFileName` is the name of the file that holds words not allowed in chat, so yes the black list of words. If you do `[p]bs badword` it will be added to this file. The separator is newline `\n`. As for the random banning, if a user sends messages less than 1 second apart, it would lead to a ban. This was done in an attempt to prevent spamming. You can try with a lower value here https://github.com/nortxort/nortbot/blob/954f322279457d47531da2bd40cfb2335798af62/handlers/check.py#L214 maybe change the `999999` to `500000`. This would mean, if a user sends messages less than half a second apart, then ban that user.

@Technetium1 You are referencing the join/message time limit.

**Comment by kytwb** [comment]
@nortxort thank you!

**Comment by Technetium1** [comment]
@kytwb Did changing it solve the bans?
@nortxort Thanks, accidentally perma-linked the wrong line 🤦‍♂️

**Comment by kytwb** [comment]
@Technetium1 I removed the condition that returned `True` that @nortxort pointed out completely. Might want to make that a togglable/documented feature.
