### ISSUE TITLE
Issue with building bot

### ISSUE THREAD

**Issue by joemisfit** [nortxort/nortbot#2]
Hey Nort, 

I saw your bot recently updated, and I was wondering if you have it finished yet or if it was going to be finished soon as it seems some components are missing? If you could please assist or gather a compiled version for us that would be great!

![nortbot](https://user-images.githubusercontent.com/20868143/55656844-64ee7100-57c6-11e9-9d2e-06f7dd95ce09.png)

**Comment by nortxort** [comment]
Basically all the source code files are missing, ill upload when ready.
