### ISSUE TITLE
Not really an issue but a question?

### ISSUE THREAD

**Issue by joemisfit** [nortxort/nortbot#25]
Hello,

I'm sorry for bothering you, but I was wondering if it's possible to ban people automatically that post links as I don't see that anywhere in the config and I've tried using string bans and they haven't worked for links? As an example people post other tinychat links or advertise their youtube channels and it would be nice to see them banned automatically.

Thank you.

**Comment by Technetium1** [comment]
Wildcard support for bad strings would be pretty handy.

**Comment by joemisfit** [comment]
Indeed, however even if they type the exact link that's in the ban strings it still doesn't ban them which is odd.

**Comment by Technetium1** [comment]
@joemisfit Look at the links in logs, it is probably not the same. If I want to ban a URL I have to ban *every* way it can come. TC uses [Autolinker.js](https://github.com/gregjacobs/Autolinker.js) to make every url appear the same way in chat, however the bot still sees the URL as it was originally intended.

**Comment by nortxort** [comment]
Something like `[p]bs *tinychat.com` should work?

**Comment by nortxort** [comment]
@joemisfit I can confirm that `[p]bs *tinychat.com` works as expected. I tested it with both the current version and the previous. I would suggest you check what version of the bot you are running.
