### ISSUE TITLE
Doesn't ban or check lists

### ISSUE THREAD

**Issue by Technetium1** [nortxort/nortbot#3]
## Expected behaviour.
`!ba badaccount` should say `badaccount was added to file` and `badaccount is already in the list` if it's already added.

## Actual behaviour.
It says `added to file` and doesn't write anything, or check for the existence of anything

## Steps to reproduce behaviour.
`Tech: !ba badaccount`
` _: badaccount was added to file.`
`Tech: !ba badaccount`
`_: badaccount was added to file.`
`Tech: !rmba badaccount`

## Notes/Code/Other information.
This also happens with bad strings, including the non-response to removing from the list. Bad nicks are working however.

**Comment by nortxort** [comment]
Looks like i made a mistake in the NortBot.get_list method, it should be

    def get_list(self, approved=False, nicks=False,
                 accounts=False, strings=False):
        """
        Read bot specific files to memory.

        :param approved: Read the approved accounts file.
        :type approved: bool
        :param nicks: Read the nick bans file.
        :type nicks: bool
        :param accounts: Read the account bans file.
        :type accounts: bool
        :param strings: Read the string bans file.
        :type strings: bool
        """
        log.debug('reading file: approved=%s, nicks=%s, '
                  'accounts=%s, strings=%s' %
                  (approved, nicks, accounts, strings))

        if approved:
            CONF.APPROVED = file_handler.reader(
                self.config_path, CONF.APPROVED_FILE_NAME)
        if nicks:
            CONF.NICK_BANS = file_handler.reader(
                self.config_path, CONF.NICK_BANS_FILE_NAME)
        if accounts:
            CONF.ACCOUNT_BANS = file_handler.reader(
                self.config_path, CONF.ACCOUNT_BANS_FILE_NAME)
        if strings:
            CONF.STRING_BANS = file_handler.reader(
                self.config_path, CONF.STRING_BANS_FILE_NAME)

**Comment by Technetium1** [comment]
@nortxort this is the same code that is there now.

**Comment by nortxort** [comment]
It is not the same, see

    def get_list(self, approved=False, nicks=False,
                 accounts=False, strings=False):
        """
        Read bot specific files to memory.

        :param approved: Read the approved accounts file.
        :type approved: bool
        :param nicks: Read the nick bans file.
        :type nicks: bool
        :param accounts: Read the account bans file.
        :type accounts: bool
        :param strings: Read the string bans file.
        :type strings: bool
        """
        log.debug('reading file: approved=%s, nicks=%s, '
                  'accounts=%s, strings=%s' %
                  (approved, nicks, accounts, strings))

        if approved:
            CONF.APPROVED = file_handler.reader(
                self.config_path, CONF.APPROVED_FILE_NAME)
        if nicks:
            CONF.NICK_BANS = file_handler.reader(
                self.config_path, CONF.NICK_BANS_FILE_NAME)
        if accounts:
            CONF.ACCOUNT_BANS = file_handler.reader(
                self.config_path, CONF.NICK_BANS_FILE_NAME)
        if strings:
            CONF.STRING_BANS = file_handler.reader(
                self.config_path, CONF.NICK_BANS_FILE_NAME)

Notice the `CONF.NICK_BANS_FILE_NAME` for both account and strings

**Comment by Technetium1** [comment]
Turns out I didn't look close enough, thanks for the fix!
