### ISSUE TITLE
.exe Issue/Connection Issue

### ISSUE THREAD

**Issue by gloriousone** [nortxort/nortbot#34]
Upon following the instructions and compiling the code into a .exe I have received the following message:

![errormsg](https://user-images.githubusercontent.com/51096957/58438069-f679b100-809a-11e9-88dc-8ffb902539a3.png)

There have been no changes to the pre-existing code aside from editing the config.ini

The window pops up for half of a second and then closes itself automatically. The bot doesn't launch or even make an attempt to connect, assuming because of one of these issues or error related messages. 

Have ran the all-in-one pre-compiled and it functions as intended with my current config.ini however I wanted to make a few alterations such as extending the spam-ban criteria. Clearly something you can not do with an already compiled .exe

Any solutions or suggestions to help get this thing up and running would be greatly appreciated. Marvelous piece of work and I hope you guys keep it up!

**Comment by Autotonic** [comment]
Should be fixed, please confirm and close this issue @gloriousone

**Comment by gloriousone** [comment]
Confirmed the fix. Much appreciated! 

Side note: 
UserWarning: The soupsieve package is not installed. CSS selectors cannot be used.

I have been receiving this warning and confirm soupsieve is installed and up to date. Any thoughts? Doesn't seem to affect functionality in any way I've found so far. Present in both the precompiled and the one I just compiled myself.

**Comment by Autotonic** [comment]
Yeah this can safely be ignored.
