### ISSUE TITLE
[Suggestion] Check to ignore 'spam' at or above a certain user level

### ISSUE THREAD

**Issue by gloriousone** [nortxort/nortbot#37]
While playing around with code strings I wasn't able to get the bot to accept this sort of thing. It either ended up completely ignoring all instances of spam and not banning any of them, or refusing to run once compiled.

Any thoughts? Could something like this be easily implemented or would it take extensive reworking of the pre-existing code?

**Comment by Autotonic** [comment]
@gloriousone we changed some of the issue templates, can you resubmit this using the "Feature Request"
template. Thanks!
