### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by Autotonic** [nortxort/nortbot#43]
**Is your feature request related to a problem? Please describe.**
request is related to youtube track objects

**Describe the solution you'd like**
A user withouth roles should be able to skip their own song, and only skip

**Describe alternatives you've considered**
Lol i dont read code, i guesstimate

**Comment by nortxort** [comment]
But if a user has no role, how would they add a track in the first place?

**Comment by Autotonic** [comment]
Notes:
1) Add a `User` object to YouTube, i.e. `owner = User._session_id`
2) Handle user leaves for Youtube when user object is deleted `owner = None`
3) Handle if NoneType for `owner` with Youtube playlist (see 2.)^
