### ISSUE TITLE
'list' object has no attribute 'start'

### ISSUE THREAD

**Issue by kytwb** [nortxort/nortbot#46]
Not sure what was the state of the bot, but this happened:

```
[07:<redacted>] <redacted>: !yt <normal youtube thing>
'list' object has no attribute 'start'
```

**Comment by kytwb** [comment]
Maybe following a `!cm`?

**Comment by Autotonic** [comment]
Has to be related to #22

Think i have an idea of what's going wrong. Will look into it this week.

**Comment by kytwb** [comment]
@Autotonic True, I didn't make the connection (created the ticket quickly before jumping back into work).

**Comment by Autotonic** [comment]
Merging this issue with #22
