### ISSUE TITLE
[Suggestion] Prevent playing videos that disallow embedding

### ISSUE THREAD

**Issue by Autotonic** [nortxort/nortbot#50]
**Is your feature request related to a problem? Please describe.**
Youtube videos not allowed to be embedded

**Describe the solution you'd like**
Should check if the video can be embedded or not via YouTube Data API

**Describe alternatives you've considered**
N/A?

**Additional context**
N/A

**Comment by Autotonic** [comment]
### Notes:
Need to append `status` to the details [URL](https://github.com/nortxort/nortbot/blob/master/apis/youtube.py#L87)
```diff
    _video_details_url = 'https://www.googleapis.com/youtube/v3/videos?' \
---                         'id={1}&key={0}&part=contentDetails,snippet'
    _video_details_url = 'https://www.googleapis.com/youtube/v3/videos?' \
+++                         'id={1}&key={0}&part=contentDetails,snippet,status'
```
Path to `embeddable` in json
```py
response.json['items'][0]['status']['embeddable'] -> bool
```
Need to sort out how to handle this to alert the user

**Comment by nortxort** [comment]
An attempt to fix is in [this commit](https://github.com/nortxort/nortbot/commit/b6719bf63a3c8de7f3024fd8a1dd6b3c6cbbc0e6)

**Comment by Technetium1** [comment]
That commit fixes it. I think it would be good to play the next video as well as that alert, so it's known why their video did not play and/or why the 'wrong' one played.

**Comment by nortxort** [comment]
@Technetium1 The `This track is not embeddable.` warning will only be present if its a direct search, either by link or youtube ID. Doing a normal search will just find another video.

Closing.
