### ISSUE TITLE
[Suggestion] Vote Ban / Close

### ISSUE THREAD

**Issue by Technetium1** [nortxort/nortbot#53]
**Is your feature request related to a problem? Please describe.**
*N/A*

**Describe the solution you'd like**
An option to `!voteban Nickname` and `!voteclose Nickname`, which requires a majority vote in the room. Vote should be cancelled if someone leaves or joins. Moderators/Approved users should be immune to this. *Anyone* should be able to trigger it if they've been in the room for more than 5 minutes. 

**Describe alternatives you've considered**
*N/A*

**Additional context**
Needs thorough testing before release to prevent bad things from happening.

**Comment by nortxort** [comment]
lol

**Comment by Technetium1** [comment]
Added in https://github.com/nortxort/nortbot/commit/ad6c4484b54a56cf130f22c3e3bcf42e669cad22, but I still need to test it.

**Comment by nortxort** [comment]
This have been implemented in [this](https://github.com/nortxort/nortbot/commit/ad6c4484b54a56cf130f22c3e3bcf42e669cad22), so i am gonna close this.
