### ISSUE TITLE
Public commands

### ISSUE THREAD

**Issue by Webby7866** [nortxort/nortbot#55]
fun commands as cn roll flip 8ball ect is listed as public but only mods can do them... there listed under default level how do i fix this? a guest does it it does nothing and i want them to be able to use them

**Comment by The1TrueChiver** [comment]
Did you check if "Public Commands" was set to "True" in the config.ini file? Alternatively you can enable public commands with the default command "!pub"

**Comment by Technetium1** [comment]
This was just tested and is working as expected currently.
