### ISSUE TITLE
[Bug] Ban on double space between words

### ISSUE THREAD

**Issue by Technetium1** [nortxort/nortbot#56]
**System Information**
* Operating System: Ubuntu 18.04
* Python Version [e.g. 2.7.16]

**Bot Configuration**
What have you changed in `config.ini`? (besides passwords/keys/accounts):
```ini
AutoLogin=True
ChatLogging=True
DebugMode=True
DebugToFile=True
KickAsAutoban=False
NotifyOnBan=True
TryTimeBasedCheck=False

[integers]
DebugLevel=20
MaxMatchBans=3
ThreadPool=25
```

**Describe the bug**
A user will be banned if there are 2 spaces between words.

**To Reproduce**
1. Say `test  test`.
2. Get banned.

**Expected behavior**
Should not be banned for having bad grammar.

**Tracebacks and Errors**
```py2
[21:04:23:200] nickname: test  test
[21:04:23:296] [SYSTEM]: _ banned nickname
[21:04:23:298] nickname:2447937 left the room.
```
* `debug.log` contains nothing useful.

**Comment by Autotonic** [comment]
Due to having `*/n/n` in `string_bans.txt`
```py
>>> a = "*\n\n"
>>> # in "anything you want"
>>> a.rstrip("\n").replace("*","") in ""
True
```
