### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by imtammer** [nortxort/nortbot#7]
## Expected behaviour.
CannaBot kicked Username

## Actual behaviour.
<blank>

## Steps to reproduce behaviour.
!kick Username

## Notes/Code/Other information.
command doesnt seem to be in there, can we request it? once a user account has been added to ban file it would be nice for people who are modded in the bot alone to be able to kick people.

**Comment by imtammer** [comment]
also regarding the ban feature...if there was a way to expire bans after 30 days and have others as permabanned (unless removed individually)...not sure how simple those would be to implement, but would be nice

**Comment by Technetium1** [comment]
@imtammer this was a bug with bans and kicks, and is fixed in the latest commit: https://github.com/nortxort/nortbot/commit/9134565ecf63256e2d02c65cb7761260db7ed221
