### ISSUE TITLE
Crashes when changing nickname to one containing space

### ISSUE THREAD

**Issue by kytwb** [nortxort/nortbot#9]
## Expected behaviour.

Change the nickname or properly handle edge cases and notify the user of the invalidity of the nickname.
 
## Actual behaviour.

Crashes.

## Steps to reproduce behaviour.

> !nick something with space

## Setup.

N/A

## Notes/Code/Other information.

N/A

**Comment by Technetium1** [comment]
@kytwb This should be fixed in https://github.com/nortxort/nortbot/commit/22d063a7869fffad0497314100ac4b52e0e1ca23
